-- Migration to add tier to zones and seed Chennai/Bangalore areas

-- 1. Add tier column to zones table
ALTER TABLE zones ADD COLUMN tier INTEGER;

-- 2. Define Helper for Inserting/Updating Zones
-- Note: Assuming UUIDs are generated by default or supplied. 
-- For seeding, we'll use a subquery to find the city_id.

-- CHENNAI TIER 1
INSERT INTO zones (id, city_id, name, tier, created_at)
VALUES 
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Adyar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Besant Nagar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Anna Nagar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Nungambakkam', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'T. Nagar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Alwarpet', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Mylapore', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Boat Club Road', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'RA Puram (Raja Annamalaipuram)', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'ECR (East Coast Road – premium zones)', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'OMR (IT corridor prime zones)', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Thiruvanmiyur', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Velachery (prime residential parts)', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Kilpauk', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Egmore', 1, NOW())
ON CONFLICT (city_id, name) DO UPDATE SET tier = EXCLUDED.tier;

-- CHENNAI TIER 2
INSERT INTO zones (id, city_id, name, tier, created_at)
VALUES 
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Tambaram', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Chromepet', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Porur', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Medavakkam', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Perungudi', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Pallikaranai', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Madipakkam', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Kolathur', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Ambattur', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Mogappair', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Sholinganallur', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Guduvanchery', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Navalur', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Thoraipakkam', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Valasaravakkam', 2, NOW())
ON CONFLICT (city_id, name) DO UPDATE SET tier = EXCLUDED.tier;

-- CHENNAI TIER 3
INSERT INTO zones (id, city_id, name, tier, created_at)
VALUES 
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Perambur', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Red Hills', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Avadi', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Manali', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Tondiarpet', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Washermanpet', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Ennore', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Madhavaram', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Minjur', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Poonamallee', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Gummidipoondi', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Pattabiram', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Villivakkam', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Chennai'), 'Vyasarpadi', 3, NOW())
ON CONFLICT (city_id, name) DO UPDATE SET tier = EXCLUDED.tier;

-- BANGALORE TIER 1
INSERT INTO zones (id, city_id, name, tier, created_at)
VALUES 
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Indiranagar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Koramangala', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Whitefield', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'HSR Layout', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Jayanagar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Malleshwaram', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Rajajinagar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Sadashivanagar', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Hebbal', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Richmond Town', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Lavelle Road', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Ulsoor', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Frazer Town', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Cunningham Road', 1, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'MG Road', 1, NOW())
ON CONFLICT (city_id, name) DO UPDATE SET tier = EXCLUDED.tier;

-- BANGALORE TIER 2
INSERT INTO zones (id, city_id, name, tier, created_at)
VALUES 
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'BTM Layout', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Yelahanka', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Electronic City', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Marathahalli', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Bannerghatta Road', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Kengeri', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'KR Puram', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Hoodi', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Hennur', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Kalyan Nagar', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Ramamurthy Nagar', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Nagarbhavi', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Basaveshwar Nagar', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Banashankari', 2, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Vijayanagar', 2, NOW())
ON CONFLICT (city_id, name) DO UPDATE SET tier = EXCLUDED.tier;

-- BANGALORE TIER 3
INSERT INTO zones (id, city_id, name, tier, created_at)
VALUES 
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Peenya', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Yeshwanthpur', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Nelamangala', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Devanahalli', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Doddaballapur', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Anekal', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Magadi Road outskirts', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Attibele', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Jigani', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Chikkaballapur', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Bagalur', 3, NOW()),
(gen_random_uuid(), (SELECT id FROM cities WHERE name = 'Bengaluru'), 'Chintamani outskirts', 3, NOW())
ON CONFLICT (city_id, name) DO UPDATE SET tier = EXCLUDED.tier;
