-- V7: Update Shop Schema for Vendor Details

ALTER TABLE shops
ADD COLUMN IF NOT EXISTS state VARCHAR(255),
ADD COLUMN IF NOT EXISTS pincode VARCHAR(20),
ADD COLUMN IF NOT EXISTS address VARCHAR(255),
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(20) DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS banner_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
ADD COLUMN IF NOT EXISTS business_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS category VARCHAR(100),
ADD COLUMN IF NOT EXISTS id_proof_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS business_proof_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_proof_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS cancelled_cheque_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS franchise_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
