# ===============================
# Actuator (Production)
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

admin.email=admin@jiffykart.org
admin.password=Jiffykart@2026

jiffikart.cors.allowed-origins=https://jiffykart.in,https://admin.jiffykart.in,https://vendor.jiffykart.in,https://api.jiffykart.in
jiffykart.cors.allowed-origins=https://jiffykart.in,https://admin.jiffykart.in,https://vendor.jiffykart.in,https://api.jiffykart.in