# ===============================
# Actuator (Production)
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


admin.email=admin@jiffykart.org
admin.password=Jiffykart@2026