# ===============================
# Actuator (Production)
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


jiffykart.cors.allowed-origins=https://jiffykart.in,https://admin.jiffykart.in,https://vendor.jiffykart.in,https://api.jiffykart.in